#!/bin/bash

opt=$1

function replicas(){
shift
echo "replicaNumber...${1}"
cc=`curl 'localhost:9200/_cat/indices?v'|awk '{if (NR>1) print $3}'`
for c in $cc; do
curl -XPUT "localhost:9200/${c}/_settings" -d '{
    "index": {
       "number_of_replicas": "${rep}"
    }
}'
done
}

function del(){
    cc=`curl 'localhost:9200/_cat/indices?v'|awk '{if (NR>1) print $3}'`
    read -r -p '确认删除?[y/N]' cs
    case ${cs} in
        [yY][eE][sS]|[yY])
            echo "checking...${cs}!"
            for c in $cc; do
                curl -XDELETE "localhost:9200/${c}"
            done
            ;;
        *)
            ;;
    esac

}



if [ ${opt} = 'rep' ]
then
    echo "opt replicas"
    replicas $@
    exit $?
fi

if [ ${opt} = 'del' ]
then
    echo "opt del"
    del
    exit $?
fi
