#!/bin/bash

pcount=$#
if (( pcount < 1 )) ; then
        echo no args;
        exit;
fi



#p1=$1;
#fname=`basename $1`



pdir=`cd -P $(dirname $1);pwd`

cr=(0 1 2 3 4)

for (( i=0; i<${#cr[@]};i++)) do
        echo "======================s12${cr[i]}======================"
        ssh  s12${cr[i]} bash -c "' source ~/.bash_profile && cd $pdir && $@ '"
done

exit $?
