#!/bin/bash
pcount=$# 
if (( pcount < 1 )) ; then
        echo no args;
        exit;
fi

p1=$1;
fname=`basename $p1`
echo $fname;


pdir=`cd -P $(dirname $p1) ; pwd`
echo $pdir

cuser=`whoami`

cr=(0 1 2 3 4)

for (( i=0; i<${#cr[@]};i++)) do
        echo "======================s12${cr[i]}======================"
        rsync -rvl $pdir/$fname $cuser@s12${cr[i]}:$pdir
done

exit $?

